language: java

env:
  global:
  - TRAVIS_SCALA212=2.12.10
  - TRAVIS_SCALA213=2.13.1
  - TRAVIS_SBT=1.3.3
  - TEST_FORK=true
  - secure: HFp0Jm4r+bk7CKT5YJX6rlqo0+itHfcae0gC4BY7rNrv8JN7POHs+Db2BeCwwOJXKFxHDxFjLyKwzX4LcFkBzQataUfzqHvBlkLh2XkCkMUZsOt4xhflwJZMXYihLyoX0Wct42AE4DWmBiFiC5wePI6/7/nWFk+gv0KN+X8zK0y1WdtZR6PqyFxE0NengnRB9sliiDQU2ESdZ7zuoMytbRDlcmTqj70C8ym9KGLdZvM/8R7n+5GGbkfvCXAiNnYDd2uARw/Ep4JDqM/UoXC21NqOknIHuaC3j3Rb66+wgNev+Nmfg5YU1mGWWGWSsFPTh6MVuUM84aFtoStUwsTSjvVvHTrzPyHEg4kP44Qco5fdRgDQUz+7MVOjVL4hogW0eLSiVceOle7tcN6Q5zn/5wNaKoJRJjo9Dw5zEI+w4AgEkiky/TKRnJQiqzTbLQ2kN9ALGJAHan1+Kg7SaC5GWdjm6bDFz4zjbAPYEqPosePRB9X2sxUjndTE/HYLgLLqK5yIUj06XY7YNmWOwRS83+5VzwAl82lkfaI9oXb8Giy7XiAtT0jfviAHwSx1fo1QRyBUCCPyxiLccgFLCFyaUBwwUXXBEieWJWLbRIbScj3b0RTZRtR/VZ54rz3rMzDxD9J09x7NGJvn3Ext0ampMuOcJpEHOy2akojZ60qQcV8=

matrix:
  include:
  - name: "Linux + JDK 8"
    dist: xenial
    env:
      - ADOPTOPENJDK=8
    script:
      - sbt -Dsbt.test.fork=true ++$TRAVIS_SCALA212 mimaReportBinaryIssues scalafmtCheckAll headerCheck Test/headerCheck test whitesourceCheckPolicies doc
      - sbt -Dsbt.test.fork=false ++$TRAVIS_SCALA213 test

  - name: "Linux + JDK 11"
    dist: xenial
    env:
      - ADOPTOPENJDK=11

  - name: "macOS + JDK 8"
    os: osx
    osx_image: xcode9.3
    env:
      - ADOPTOPENJDK=8

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true >> $HOME/.sdkman/etc/config
  - echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - unset _JAVA_OPTIONS

install:
  - sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - unset JAVA_HOME
  - java -Xmx32m -version
  - sdk install sbt $TRAVIS_SBT

script:
  - sbt -Dsbt.test.fork=true ++$TRAVIS_SCALA212! mimaReportBinaryIssues test
  - sbt -Dsbt.test.fork=false ++$TRAVIS_SCALA213! test

before_cache:
  - find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete
  - find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete
  - find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete
  - find $HOME/.sbt                              -name "*.lock"               -delete

cache:
  directories:
    - $HOME/Library/Caches/Coursier/v1
    - $HOME/.cache/coursier/v1
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.sdkman
